<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>2ebbf05c-7f56-4338-94ec-be4541600bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ya-myab-address-edit-btn-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-myab-address-edit-btn-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f261302d-cf73-451f-a394-1f0d06985b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/a/addresses/edit?ref=ya_address_book_edit_button&amp;addressID=F44GAQDQGRBBWP6PIB7YG12SVQJY6BTWLA21LWTB6YJQVSXPXTQ2EIA2OX266FKE</value>
      <webElementGuid>9d418bec-af30-4338-8de5-5cdfd9469cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit name</value>
      <webElementGuid>ace1346f-c861-4a8d-a22e-28a56dcfeb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>f4a575a1-d534-44b7-aa34-558f082f0941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit            </value>
      <webElementGuid>8ac387e4-b9bc-4afd-ac2e-0a3864611550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya-myab-address-edit-btn-0&quot;)</value>
      <webElementGuid>24ae217b-c7a3-4290-952b-6731994f6dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-myab-address-edit-btn-0</value>
      <webElementGuid>e2125343-215d-4f4c-93d2-4110cada0a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ya-myab-address-edit-btn-0']</value>
      <webElementGuid>d47b35d4-a771-44d2-99b4-85da720a8770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ya-myab-edit-address-desktop-row-0']/a</value>
      <webElementGuid>f8d933db-4998-40cd-8049-4ed42434482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>5f0a5a5f-cabc-4f02-b0b4-b7ebe6b444d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/a/addresses/edit?ref=ya_address_book_edit_button&amp;addressID=F44GAQDQGRBBWP6PIB7YG12SVQJY6BTWLA21LWTB6YJQVSXPXTQ2EIA2OX266FKE')]</value>
      <webElementGuid>3aac6de2-9346-40b6-b62a-5591ab8d6c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>d6704b67-c1a6-48fb-9a8b-d5d0fa902a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ya-myab-address-edit-btn-0' and @href = '/a/addresses/edit?ref=ya_address_book_edit_button&amp;addressID=F44GAQDQGRBBWP6PIB7YG12SVQJY6BTWLA21LWTB6YJQVSXPXTQ2EIA2OX266FKE' and (text() = 'Edit            ' or . = 'Edit            ')]</value>
      <webElementGuid>eb2dcb58-8bc4-4240-9a25-4651fedd0aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='NAME_BUTTON']/span/a</value>
      <webElementGuid>5de7c390-5763-471d-a534-5ca9d78c2e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ap/profile/name?ref_=ax_am_landing_change_name&amp;openid.assoc_handle=inflex')]</value>
      <webElementGuid>e83c9ec4-3481-415d-94af-4c3a192e47cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/a</value>
      <webElementGuid>e688a8c2-3268-4d38-94e9-323fc5d3dba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ap/profile/name?ref_=ax_am_landing_change_name&amp;openid.assoc_handle=inflex' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>48e2d92b-10f2-4ae6-a98a-dd0129bf302a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
