<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hello, PIC  Account  Lists</name>
   <tag></tag>
   <elementGuidId>9c6b91a7-7f79-43b9-8a83-dc0af63a13c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-link-accountList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-link-accountList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a06e15a2-ab1e-4e77-ab24-440b51f094b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.in/gp/css/homepage.html?ref_=nav_youraccount_btn</value>
      <webElementGuid>73ce7b35-e2b6-4cf1-af0c-d8ae3ffb593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a nav-a-2 nav-truncate   nav-progressive-attribute nav-active</value>
      <webElementGuid>9c403bff-1415-4029-92c5-3adb51a2dac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-ref</name>
      <type>Main</type>
      <value>nav_youraccount_btn</value>
      <webElementGuid>ee7013e8-4df3-4ae7-ada3-f6a3d1d23936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav-role</name>
      <type>Main</type>
      <value>signin</value>
      <webElementGuid>0ecb7299-641c-41a9-8fb4-c8ea49d35a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ux-jq-mouseenter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8611b4c-6422-4666-8b60-72fccb82ecb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-accountList</value>
      <webElementGuid>ab93d8ea-cae3-443f-8115-33a85c1f3e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16a68206-4b5c-4d71-afa1-5486a127de1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>dcd70e58-0663-4258-90ff-d99112576e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav-link-accountList</value>
      <webElementGuid>fed0c00b-7f0d-4fac-8c41-8ec10fe86b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_youraccount_btn</value>
      <webElementGuid>827064fc-f2b3-48a7-9bef-c04735bc4813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>6pu78u-r1pt77-oqt9aa-v6lmdr</value>
      <webElementGuid>256d76ca-def1-4f02-b3c8-588200d9f188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Hello, PIC
  Account &amp; Lists
  
</value>
      <webElementGuid>93741e9b-2b0d-46f6-aa70-9ae29781b9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-accountList&quot;)</value>
      <webElementGuid>691c430d-ee65-43c0-bc75-7a5f96e2c7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-link-accountList']</value>
      <webElementGuid>9c7c6f8e-6202-4907-bd23-dbe0cceb4c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tools']/a[2]</value>
      <webElementGuid>bd36b132-464b-40a7-af23-61b31dc23e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.in/gp/css/homepage.html?ref_=nav_youraccount_btn')]</value>
      <webElementGuid>8d759b83-0ceb-4cf7-afa3-05d39b11db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a[2]</value>
      <webElementGuid>667a0e23-74d4-406b-994b-9dbf8cc7e723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.in/gp/css/homepage.html?ref_=nav_youraccount_btn' and @id = 'nav-link-accountList' and (text() = '
  Hello, PIC
  Account &amp; Lists
  
' or . = '
  Hello, PIC
  Account &amp; Lists
  
')]</value>
      <webElementGuid>ba36a42c-7d83-474c-a0f1-df74d59d5897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
