<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divya-myab-plus-address-icon</name>
   <tag></tag>
   <elementGuidId>f4738203-071e-4fd6-83d6-9c3c9703e659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ya-myab-plus-address-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-myab-plus-address-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6f5851d-43df-4e67-b0d4-60eed97a68e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-myab-plus-address-icon</value>
      <webElementGuid>9d43d28b-0eed-4a77-bb01-4d2c343ca0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-section a-spacing-none address-plus-icon aok-inline-block</value>
      <webElementGuid>9f40408f-325b-4db0-a606-027184b3f7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya-myab-plus-address-icon&quot;)</value>
      <webElementGuid>9ee4fca9-9432-4a73-9205-109f1aae8d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ya-myab-plus-address-icon']</value>
      <webElementGuid>3761109e-f8ec-458a-b137-aba7428628e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ya-myab-address-add-link']/div/div/div</value>
      <webElementGuid>69e7e887-4ba5-4acf-8c14-5f32646449bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div</value>
      <webElementGuid>0676cb53-691c-4d48-8a91-bea1e3c5d372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ya-myab-plus-address-icon']</value>
      <webElementGuid>d96edcd7-4e70-4edc-9a28-8edbb01e0aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
