<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_TestSuite_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0994cd32-3815-4a90-9f70-37f32d63d1e7</testSuiteGuid>
   <testCaseLink>
      <guid>dac3dcca-9fd4-466b-893d-b8973285954d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>cd38f3f4-ed25-481a-b7d6-a9b3b447162d</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Amazon_Login/TC_Amazon_Login_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>22b701d7-8999-457d-afdb-5018c44e88ec</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_LoginData/Amazon_Login_Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>22b701d7-8999-457d-afdb-5018c44e88ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>cd38f3f4-ed25-481a-b7d6-a9b3b447162d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>22b701d7-8999-457d-afdb-5018c44e88ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>86da5672-2d8d-484b-a6b6-63bdb7e5152b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bad4dfe-0858-4e1c-8955-632fe0f40277</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>d2b1c619-9c59-4d81-a1fd-8f7a43d6623d</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Amazon_Login/TC_Amazon_Login_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>56f82c94-27aa-4406-b7d8-60e43cbe8df3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Amazon_LoginData/Amazon_Login_Data_002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>56f82c94-27aa-4406-b7d8-60e43cbe8df3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>d2b1c619-9c59-4d81-a1fd-8f7a43d6623d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>56f82c94-27aa-4406-b7d8-60e43cbe8df3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f62beff7-794b-4f0e-8250-db863e5feb94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8d3a15fa-fd83-4b3d-ac7c-313d578482d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Amazon_Login/TC_Amazon_Login_003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
